/**
 * Predefined Job Roles with required skills for the matching engine.
 * Each role lists the skills that are relevant for that position.
 * Skills are matched against the user's extracted skills (case-insensitive).
 */

const JOB_ROLES = [
  {
    title: "Data Analyst",
    requiredSkills: [
      "sql",
      "excel",
      "python",
      "pandas",
      "numpy",
      "tableau",
      "power bi",
      "data analysis",
      "data visualization",
      "statistics",
      "etl",
      "bigquery",
      "looker",
      "metabase",
      "r",
      "matplotlib",
      "seaborn",
      "google sheets",
      "sql server",
      "postgresql",
      "mysql",
      "mongodb",
      "data cleaning",
      "data wrangling",
      "reporting",
      "dashboards",
      "kpis",
      "metrics",
      "analytics",
      "business intelligence",
      "hypothesis testing",
      "a/b testing",
      "time series",
      "forecasting",
      "predictive analytics",
      "data modeling",
      "data mining",
      "data engineering",
      "spark",
      "hive",
      "presto",
      "trino",
      "druid",
      "clickhouse",
      "redshift",
      "snowflake",
      "databricks",
      "teradata",
      "vertica",
      "sap hana",
      "hana",
      "dax",
      "vba",
      "sas",
      "stata",
      "spss",
      "communication",
      "problem solving",
      "critical thinking",
      "attention to detail",
      "data-driven",
      "data-driven decision making",
    ],
  },
  {
    title: "Machine Learning Engineer",
    requiredSkills: [
      "python",
      "machine learning",
      "deep learning",
      "tensorflow",
      "pytorch",
      "keras",
      "scikit-learn",
      "numpy",
      "pandas",
      "nlp",
      "computer vision",
      "reinforcement learning",
      "neural network",
      "cnn",
      "rnn",
      "lstm",
      "transformer",
      "bert",
      "gpt",
      "llm",
      "rag",
      "fine-tuning",
      "prompt engineering",
      "mlops",
      "mlflow",
      "kubeflow",
      "docker",
      "kubernetes",
      "aws",
      "azure",
      "gcp",
      "data pipeline",
      "feature engineering",
      "model evaluation",
      "cross-validation",
      "hyperparameter tuning",
      "ensemble learning",
      "gradient boosting",
      "xgboost",
      "lightgbm",
      "catboost",
      "random forest",
      "decision tree",
      "linear regression",
      "logistic regression",
      "support vector machine",
      "k-nearest neighbors",
      "naive bayes",
      "k-means",
      "pca",
      "time series",
      "forecasting",
      "statistics",
      "probability",
      "linear algebra",
      "calculus",
      "data engineering",
      "spark",
      "kafka",
      "airflow",
      "distributed systems",
      "parallel computing",
      "gpu programming",
      "cuda",
      "tensorrt",
      "onnx",
      "openvino",
      "edge ai",
      "model deployment",
      "api",
      "fastapi",
      "flask",
      "django",
      "rest api",
      "grpc",
      "problem solving",
      "critical thinking",
      "communication",
      "collaboration",
      "teamwork",
      "agile",
      "scrum",
      "git",
      "github",
      "linux",
      "bash",
      "jupyter",
      "git",
      "docker-compose",
      "terraform",
      "pulumi",
      "serverless",
      "lambda",
      "sagemaker",
      "vertex ai",
      "azure ml",
      "databricks",
      "mlops",
      "ci/cd",
      "jenkins",
      "github actions",
    ],
  },
  {
    title: "Python Developer",
    requiredSkills: [
      "python",
      "django",
      "flask",
      "fastapi",
      "rest api",
      "sql",
      "postgresql",
      "mysql",
      "sqlite",
      "mongodb",
      "redis",
      "celery",
      "rabbitmq",
      "docker",
      "kubernetes",
      "aws",
      "azure",
      "gcp",
      "git",
      "github",
      "gitlab",
      "unit testing",
      "pytest",
      "unittest",
      "tdd",
      "ci/cd",
      "linux",
      "bash",
      "javascript",
      "typescript",
      "html",
      "css",
      "react",
      "vue",
      "graphql",
      "websocket",
      "microservices",
      "api design",
      "swagger",
      "openapi",
      "sqlalchemy",
      "peewee",
      "async",
      "asyncio",
      "aiohttp",
      "tornado",
      "bottle",
      "pyramid",
      "web scraping",
      "beautifulsoup",
      "selenium",
      "scrapy",
      "automation",
      "scripting",
      "numpy",
      "pandas",
      "machine learning",
      "data science",
      "data analysis",
      "problem solving",
      "communication",
      "teamwork",
      "agile",
      "scrum",
      "jira",
      "confluence",
    ],
  },
  {
    title: "Full Stack Developer",
    requiredSkills: [
      "javascript",
      "typescript",
      "html",
      "css",
      "react",
      "react.js",
      "reactjs",
      "angular",
      "vue",
      "svelte",
      "next.js",
      "node.js",
      "express",
      "django",
      "flask",
      "fastapi",
      "spring",
      "spring boot",
      "ruby on rails",
      "laravel",
      "php",
      "python",
      "java",
      "c#",
      "go",
      "rust",
      "sql",
      "postgresql",
      "mysql",
      "mongodb",
      "redis",
      "graphql",
      "rest api",
      "websocket",
      "docker",
      "kubernetes",
      "aws",
      "azure",
      "gcp",
      "firebase",
      "supabase",
      "git",
      "github",
      "gitlab",
      "jest",
      "mocha",
      "cypress",
      "selenium",
      "playwright",
      "pytest",
      "junit",
      "ci/cd",
      "github actions",
      "jenkins",
      "webpack",
      "vite",
      "tailwind",
      "tailwind css",
      "bootstrap",
      "material-ui",
      "mui",
      "redux",
      "react-query",
      "microservices",
      "system design",
      "api design",
      "swagger",
      "openapi",
      "linux",
      "bash",
      "agile",
      "scrum",
      "kanban",
      "jira",
      "problem solving",
      "communication",
      "teamwork",
      "collaboration",
    ],
  },
  {
    title: "Data Engineer",
    requiredSkills: [
      "python",
      "java",
      "scala",
      "sql",
      "etl",
      "elt",
      "spark",
      "apache spark",
      "hadoop",
      "kafka",
      "apache kafka",
      "airflow",
      "apache airflow",
      "flink",
      "storm",
      "data pipeline",
      "data warehouse",
      "data lake",
      "data lakehouse",
      "big data",
      "postgresql",
      "mysql",
      "mongodb",
      "cassandra",
      "redis",
      "elasticsearch",
      "dynamodb",
      "redshift",
      "bigquery",
      "snowflake",
      "databricks",
      "hive",
      "presto",
      "trino",
      "druid",
      "clickhouse",
      "s3",
      "cloud storage",
      "aws",
      "azure",
      "gcp",
      "docker",
      "kubernetes",
      "terraform",
      "git",
      "github",
      "gitlab",
      "ci/cd",
      "data modeling",
      "dimensional modeling",
      "star schema",
      "snowflake schema",
      "data governance",
      "data quality",
      "data lineage",
      "data catalog",
      "data security",
      "data privacy",
      "data engineering",
      "data analysis",
      "data science",
      "machine learning",
      "python",
      "pandas",
      "numpy",
      "spark sql",
      "sql server",
      "oracle",
      "sap hana",
      "hana",
      "teradata",
      "vertica",
      "dbt",
      "dbt",
      "looker",
      "tableau",
      "power bi",
      "dashboards",
      "reporting",
      "problem solving",
      "communication",
      "teamwork",
      "collaboration",
      "agile",
      "scrum",
    ],
  },
  {
    title: "DevOps Engineer",
    requiredSkills: [
      "docker",
      "kubernetes",
      "k8s",
      "helm",
      "terraform",
      "pulumi",
      "ansible",
      "chef",
      "puppet",
      "jenkins",
      "github actions",
      "gitlab ci",
      "circleci",
      "travis ci",
      "azure devops",
      "azure pipelines",
      "ci/cd",
      "aws",
      "azure",
      "gcp",
      "lambda",
      "ec2",
      "s3",
      "cloudformation",
      "serverless",
      "nginx",
      "apache",
      "linux",
      "bash",
      "python",
      "go",
      "git",
      "github",
      "gitlab",
      "argocd",
      "argo",
      "flux",
      "spinnaker",
      "prometheus",
      "grafana",
      "datadog",
      "new relic",
      "splunk",
      "elasticsearch",
      "loki",
      "cloudwatch",
      "azure monitor",
      "monitoring",
      "logging",
      "observability",
      "opentelemetry",
      "vpc",
      "iam",
      "networking",
      "load balancing",
      "dns",
      "firewall",
      "security",
      "vault",
      "consul",
      "etcd",
      "nginx",
      "caddy",
      "traefik",
      "envoy",
      "istio",
      "service mesh",
      "kubectl",
      "minikube",
      "kind",
      "k3s",
      "docker compose",
      "docker-compose",
      "dockerfile",
      "container",
      "podman",
      "containerd",
      "vagrant",
      "packer",
      "scripts",
      "automation",
      "infrastructure as code",
      "iac",
      "problem solving",
      "communication",
      "teamwork",
      "agile",
      "scrum",
      "kanban",
    ],
  },
  {
    title: "Frontend Developer",
    requiredSkills: [
      "javascript",
      "typescript",
      "html",
      "css",
      "react",
      "react.js",
      "reactjs",
      "angular",
      "vue",
      "svelte",
      "next.js",
      "gatsby",
      "redux",
      "redux toolkit",
      "mobx",
      "zustand",
      "tailwind",
      "tailwind css",
      "bootstrap",
      "material-ui",
      "mui",
      "chakra ui",
      "styled-components",
      "sass",
      "scss",
      "less",
      "webpack",
      "vite",
      "rollup",
      "babel",
      "eslint",
      "prettier",
      "jest",
      "vitest",
      "cypress",
      "playwright",
      "puppeteer",
      "testing library",
      "react testing library",
      "graphql",
      "rest api",
      "websocket",
      "node.js",
      "express",
      "git",
      "github",
      "gitlab",
      "figma",
      "responsive design",
      "accessibility",
      "a11y",
      "ui/ux",
      "performance optimization",
      "seo",
      "progressive web app",
      "pwa",
      "frontend",
      "front-end",
      "agile",
      "scrum",
      "kanban",
      "jira",
      "problem solving",
      "communication",
      "teamwork",
      "collaboration",
      "attention to detail",
    ],
  },
  {
    title: "Backend Developer",
    requiredSkills: [
      "node.js",
      "express",
      "python",
      "django",
      "flask",
      "fastapi",
      "java",
      "spring",
      "spring boot",
      "go",
      "golang",
      "c#",
      "php",
      "laravel",
      "ruby",
      "rails",
      "ruby on rails",
      "graphql",
      "rest api",
      "microservices",
      "sql",
      "postgresql",
      "mysql",
      "mongodb",
      "redis",
      "rabbitmq",
      "kafka",
      "docker",
      "kubernetes",
      "aws",
      "azure",
      "gcp",
      "system design",
      "api design",
      "swagger",
      "openapi",
      "ci/cd",
      "git",
      "github",
      "gitlab",
      "unit testing",
      "integration testing",
      "security",
      "authentication",
      "authorization",
      "jwt",
      "oauth",
      "linux",
      "bash",
      "typescript",
      "javascript",
      "caching",
      "database design",
      "data modeling",
      "message queues",
      "webhooks",
      "performance optimization",
      "scalability",
      "agile",
      "scrum",
      "problem solving",
      "communication",
      "teamwork",
    ],
  },
  {
    title: "Mobile Developer",
    requiredSkills: [
      "swift",
      "kotlin",
      "java",
      "objective-c",
      "flutter",
      "dart",
      "react native",
      "android",
      "ios",
      "xcode",
      "android studio",
      "c#",
      "xamarin",
      "ionic",
      "cordova",
      "javascript",
      "typescript",
      "redux",
      "mobx",
      "rest api",
      "graphql",
      "firebase",
      "supabase",
      "sqlite",
      "realm",
      "api design",
      "git",
      "github",
      "gitlab",
      "testing",
      "espresso",
      "xcuitest",
      "appium",
      "detox",
      "ci/cd",
      "material design",
      "ui/ux",
      "responsive design",
      "accessibility",
      "performance optimization",
      "app store",
      "google play",
      "agile",
      "scrum",
      "problem solving",
      "communication",
      "teamwork",
    ],
  },
  {
    title: "Cloud Engineer",
    requiredSkills: [
      "aws",
      "azure",
      "gcp",
      "amazon web services",
      "microsoft azure",
      "google cloud",
      "google cloud platform",
      "docker",
      "kubernetes",
      "k8s",
      "helm",
      "terraform",
      "pulumi",
      "cloudformation",
      "aws cdk",
      "serverless",
      "lambda",
      "cloud functions",
      "ec2",
      "s3",
      "cloud storage",
      "rds",
      "cloud sql",
      "dynamodb",
      "bigtable",
      "redshift",
      "bigquery",
      "vpc",
      "iam",
      "networking",
      "load balancing",
      "cloudfront",
      "route 53",
      "dns",
      "cloudwatch",
      "cloud monitoring",
      "cloud logging",
      "cloud cdn",
      "cloud armor",
      "cloud iam",
      "cloud kms",
      "secret manager",
      "azure functions",
      "azure app service",
      "azure kubernetes service",
      "aks",
      "azure blob storage",
      "azure cosmos db",
      "azure sql",
      "azure active directory",
      "azure key vault",
      "azure monitor",
      "gke",
      "cloud run",
      "cloud functions",
      "app engine",
      "kubernetes",
      "docker",
      "linux",
      "bash",
      "python",
      "go",
      "git",
      "github",
      "gitlab",
      "ci/cd",
      "jenkins",
      "github actions",
      "azure devops",
      "observability",
      "monitoring",
      "logging",
      "security",
      "cost optimization",
      "problem solving",
      "communication",
      "teamwork",
      "agile",
      "scrum",
    ],
  },
  {
    title: "AI Engineer",
    requiredSkills: [
      "python",
      "machine learning",
      "deep learning",
      "artificial intelligence",
      "nlp",
      "natural language processing",
      "computer vision",
      "reinforcement learning",
      "tensorflow",
      "pytorch",
      "keras",
      "jax",
      "scikit-learn",
      "numpy",
      "pandas",
      "transformers",
      "hugging face",
      "langchain",
      "llama",
      "llm",
      "large language model",
      "large language models",
      "gpt",
      "bert",
      "rag",
      "retrieval augmented generation",
      "fine-tuning",
      "prompt engineering",
      "embedding",
      "embeddings",
      "vector database",
      "pgvector",
      "pinecone",
      "weaviate",
      "qdrant",
      "chroma",
      "mlops",
      "mlflow",
      "docker",
      "kubernetes",
      "aws",
      "azure",
      "gcp",
      "sagemaker",
      "vertex ai",
      "azure ml",
      "api",
      "fastapi",
      "flask",
      "rest api",
      "grpc",
      "data pipeline",
      "feature engineering",
      "model evaluation",
      "model deployment",
      "data science",
      "data analysis",
      "statistics",
      "probability",
      "calculus",
      "linear algebra",
      "git",
      "github",
      "gitlab",
      "problem solving",
      "critical thinking",
      "communication",
      "collaboration",
      "teamwork",
    ],
  },
  {
    title: "Software Engineer",
    requiredSkills: [
      "javascript",
      "typescript",
      "python",
      "java",
      "c++",
      "c#",
      "go",
      "golang",
      "ruby",
      "php",
      "swift",
      "kotlin",
      "rust",
      "scala",
      "sql",
      "data structures",
      "algorithms",
      "system design",
      "object oriented programming",
      "oop",
      "design patterns",
      "data structures and algorithms",
      "dsa",
      "rest api",
      "graphql",
      "microservices",
      "docker",
      "kubernetes",
      "aws",
      "azure",
      "gcp",
      "git",
      "github",
      "gitlab",
      "unit testing",
      "integration testing",
      "tdd",
      "ci/cd",
      "jenkins",
      "github actions",
      "linux",
      "bash",
      "agile",
      "scrum",
      "kanban",
      "jira",
      "problem solving",
      "critical thinking",
      "communication",
      "collaboration",
      "teamwork",
      "leadership",
    ],
  },
];

module.exports = { JOB_ROLES };