/**
 * Skill Extraction Utility
 * Parses raw resume text into structured skill categories.
 *
 * Uses curated keyword dictionaries to match skills mentioned in
 * resume text. Matching is case-insensitive and robust to
 * whitespace/formatting variations.
 */

// Skill dictionaries organized by category (lowercase keywords).
const SKILL_DICTIONARY = {
  Languages: [
    "javascript",
    "typescript",
    "python",
    "java",
    "c++",
    "c#",
    "c",
    "ruby",
    "php",
    "go",
    "golang",
    "rust",
    "swift",
    "kotlin",
    "scala",
    "perl",
    "r",
    "dart",
    "sql",
    "html",
    "css",
    "bash",
    "shell",
    "powershell",
    "matlab",
    "groovy",
    "lua",
    "haskell",
    "elixir",
    "clojure",
    "objective-c",
    "visual basic",
    "vb.net",
    "assembly",
    "cobol",
    "fortran",
    "delphi",
    "pascal",
    "julia",
    "solidity",
    "graphql",
    "nosql",
    "pl/sql",
    "t-sql",
    "dax",
    "vba",
    "abap",
    "sas",
    "stata",
    "spss",
    "labview",
    "verilog",
    "vhdl",
    "systemverilog",
    "zig",
    "nim",
    "crystal",
    "reason",
    "ocaml",
    "f#",
    "ada",
    "smalltalk",
    "erlang",
    "prolog",
    "lisp",
    "scheme",
    "racket",
    "common lisp",
    "clojurescript",
    "elm",
    "purescript",
    "rescript",
    "gleam",
    "mojo",
    "carbon",
    "v",
    "gleam",
    "typst",
    "latex",
    "markdown",
  ],
  Frameworks: [
    "react",
    "react.js",
    "reactjs",
    "angular",
    "vue",
    "svelte",
    "next.js",
    "nextjs",
    "nuxt",
    "gatsby",
    "ember",
    "django",
    "flask",
    "fastapi",
    "spring",
    "spring boot",
    "laravel",
    "symfony",
    "rails",
    "ruby on rails",
    "express",
    "node.js",
    "nodejs",
    "deno",
    "asp.net",
    ".net",
    "asp.net core",
    "flutter",
    "react native",
    "ionic",
    "electron",
    "jquery",
    "bootstrap",
    "tailwind",
    "tailwind css",
    "material-ui",
    "mui",
    "chakra ui",
    "ant design",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "keras",
    "opencv",
    "hugging face",
    "transformers",
    "langchain",
    "spark",
    "apache spark",
    "hadoop",
    "kafka",
    "apache kafka",
    "airflow",
    "celery",
    "rabbitmq",
    "redis",
    "elasticsearch",
    "kibana",
    "apollo",
    "rest api",
    "restful",
    "grpc",
    "websocket",
    "socket.io",
    "three.js",
    "d3.js",
    "d3js",
    "chart.js",
    "recharts",
    "highcharts",
    "leaflet",
    "mapbox",
    "unity",
    "unreal",
    "godot",
    "phaser",
    "qt",
    "javafx",
    "spring mvc",
    "struts",
    "quarkus",
    "micronaut",
    "grails",
    "codeigniter",
    "slim",
    "lumen",
    "meteor",
    "preact",
    "alpine.js",
    "htmx",
    "livewire",
    "inertia",
    "blade",
    "handlebars",
    "mustache",
    "ejs",
    "pug",
    "jinja",
    "jinja2",
    "twig",
    "thymeleaf",
    "jsp",
    "tornado",
    "pyramid",
    "bottle",
    "aiohttp",
    "starlette",
    "sanic",
    "streamlit",
    "gradio",
    "dash",
    "plotly",
    "matplotlib",
    "seaborn",
    "shiny",
    "dplyr",
    "ggplot2",
    "tidyverse",
    "xgboost",
    "lightgbm",
    "catboost",
    "statsmodels",
    "scipy",
    "nltk",
    "spacy",
    "gensim",
    "tableau",
    "power bi",
    "qlik",
    "looker",
    "metabase",
    "superset",
    "grafana",
    "splunk",
    "datadog",
    "prometheus",
    "selenium",
    "cypress",
    "playwright",
    "puppeteer",
    "jest",
    "mocha",
    "chai",
    "jasmine",
    "vitest",
    "pytest",
    "cucumber",
    "junit",
    "testng",
    "mockito",
    "gtest",
    "nunit",
    "xunit",
    "phpunit",
    "rspec",
    "capybara",
    "appium",
    "espresso",
    "jmeter",
    "postman",
    "swagger",
    "openapi",
    "protobuf",
    "hive",
    "presto",
    "trino",
    "druid",
    "clickhouse",
    "influxdb",
    "cassandra",
    "couchbase",
    "couchdb",
    "mongodb",
    "mongoose",
    "prisma",
    "typeorm",
    "sequelize",
    "knex",
    "sqlalchemy",
    "postgresql",
    "postgres",
    "sqlite",
    "mysql",
    "mariadb",
    "sql server",
    "mssql",
    "oracle",
    "neo4j",
    "arangodb",
    "dynamodb",
    "firestore",
    "bigtable",
    "hbase",
    "scylladb",
    "cockroachdb",
    "supabase",
    "firebase",
    "etcd",
    "consul",
    "zookeeper",
    "nats",
    "pulsar",
    "activemq",
    "redux",
    "redux toolkit",
    "mobx",
    "zustand",
    "recoil",
    "jotai",
    "pinia",
    "vuex",
    "ngrx",
    "rxjs",
    "xstate",
    "formik",
    "react-hook-form",
    "yup",
    "zod",
    "joi",
    "ajv",
    "webpack",
    "vite",
    "rollup",
    "esbuild",
    "parcel",
    "babel",
    "swc",
    "turbo",
    "nx",
    "lerna",
    "yarn",
    "pnpm",
    "npm",
    "gulp",
    "grunt",
    "snowpack",
    "prettier",
    "eslint",
    "stylelint",
    "husky",
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "jenkins",
    "github actions",
    "gitlab ci",
    "circleci",
    "travis ci",
    "teamcity",
    "buildkite",
    "azure devops",
    "azure pipelines",
    "docker",
    "kubernetes",
    "k8s",
    "helm",
    "kustomize",
    "terraform",
    "pulumi",
    "ansible",
    "chef",
    "puppet",
    "saltstack",
    "vagrant",
    "packer",
    "cloudformation",
    "aws cdk",
    "serverless",
    "lambda",
    "ec2",
    "s3",
    "rds",
    "redshift",
    "athena",
    "glue",
    "emr",
    "kinesis",
    "sns",
    "sqs",
    "api gateway",
    "cloudfront",
    "route 53",
    "vpc",
    "iam",
    "cloudwatch",
    "azure",
    "azure functions",
    "azure app service",
    "azure kubernetes service",
    "aks",
    "azure blob storage",
    "azure cosmos db",
    "azure sql",
    "azure synapse",
    "azure data factory",
    "azure databricks",
    "azure event hubs",
    "azure service bus",
    "azure logic apps",
    "azure api management",
    "azure active directory",
    "azure key vault",
    "azure monitor",
    "azure application insights",
    "gcp",
    "google cloud",
    "google cloud platform",
    "bigquery",
    "pub/sub",
    "dataflow",
    "dataproc",
    "cloud storage",
    "cloud functions",
    "cloud run",
    "gke",
    "google kubernetes engine",
    "vertex ai",
    "firebase",
    "app engine",
    "cloud sql",
    "spanner",
    "cloud spanner",
    "cloud bigtable",
    "cloud pubsub",
    "cloud datastore",
    "cloud firestore",
    "cloud memorystore",
    "cloud tasks",
    "cloud scheduler",
    "cloud cdn",
    "load balancing",
    "cloud armor",
    "cloud iam",
    "cloud kms",
    "secret manager",
    "cloud monitoring",
    "cloud logging",
    "cloud trace",
    "cloud debugger",
    "cloud profiler",
    "cloud composer",
    "cloud build",
    "cloud deploy",
    "artifact registry",
    "container registry",
    "cloud nat",
    "cloud router",
    "virtual private cloud",
    "vpc",
    "shared vpc",
    "peering",
    "global load balancer",
    "http(s) load balancer",
    "ssl proxy",
    "tcp proxy",
    "network",
    "subnet",
    "firewall",
    "nat",
    "vpn",
    "interconnect",
    "dns",
    "cloud dns",
  ],
  Tools: [
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "jira",
    "confluence",
    "slack",
    "trello",
    "asana",
    "monday.com",
    "notion",
    "figma",
    "sketch",
    "adobe xd",
    "photoshop",
    "illustrator",
    "premiere pro",
    "after effects",
    "invision",
    "zeplin",
    "framer",
    "canva",
    "vs code",
    "visual studio",
    "intellij",
    "pycharm",
    "webstorm",
    "eclipse",
    "netbeans",
    "sublime text",
    "atom",
    "vim",
    "neovim",
    "emacs",
    "xcode",
    "android studio",
    "unity",
    "unreal engine",
    "docker",
    "kubernetes",
    "k8s",
    "helm",
    "kubectl",
    "openshift",
    "rancher",
    "minikube",
    "kind",
    "k3s",
    "vagrant",
    "jenkins",
    "circleci",
    "travis ci",
    "github actions",
    "gitlab ci",
    "azure devops",
    "teamcity",
    "bamboo",
    "buildkite",
    "codeship",
    "drone",
    "argo",
    "argocd",
    "flux",
    "spinnaker",
    "ansible",
    "terraform",
    "pulumi",
    "cloudformation",
    "chef",
    "puppet",
    "saltstack",
    "packer",
    "consul",
    "vault",
    "hashicorp",
    "nomad",
    "boundary",
    "waypoint",
    "postman",
    "insomnia",
    "swagger",
    "openapi",
    "raml",
    "jmeter",
    "k6",
    "gatling",
    "locust",
    "soapui",
    "charles proxy",
    "fiddler",
    "wireshark",
    "burp suite",
    "owasp zap",
    "nmap",
    "metasploit",
    "kali linux",
    "nessus",
    "qualys",
    "splunk",
    "elastic stack",
    "elk",
    "kibana",
    "logstash",
    "grafana",
    "prometheus",
    "datadog",
    "new relic",
    "dynatrace",
    "appdynamics",
    "pagerduty",
    "opsgenie",
    "victorops",
    "sentry",
    "bugsnag",
    "rollbar",
    "papertrail",
    "loggly",
    "sumo logic",
    "loki",
    "jaeger",
    "zipkin",
    "opentelemetry",
    "pendo",
    "amplitude",
    "mixpanel",
    "segment",
    "google analytics",
    "gtm",
    "google tag manager",
    "hotjar",
    "crazy egg",
    "fullstory",
    "optimizely",
    "vwo",
    "hubspot",
    "salesforce",
    "marketo",
    "pardot",
    "mailchimp",
    "klaviyo",
    "sendgrid",
    "twilio",
    "stripe",
    "paypal",
    "braintree",
    "square",
    "shopify",
    "woocommerce",
    "magento",
    "wordpress",
    "drupal",
    "joomla",
    "wix",
    "squarespace",
    "webflow",
    "ghost",
    "medium",
    "substack",
    "linktree",
    "zapier",
    "make",
    "integromat",
    "n8n",
    "airtable",
    "monday",
    "clickup",
    "wrike",
    "basecamp",
    "teamwork",
    "proofhub",
    "workfront",
    "smartsheet",
    "sheets",
    "excel",
    "google sheets",
    "powerpoint",
    "google slides",
    "word",
    "google docs",
    "outlook",
    "gmail",
    "calendar",
    "zoom",
    "teams",
    "microsoft teams",
    "skype",
    "webex",
    "google meet",
    "discord",
    "telegram",
    "whatsapp",
    "signal",
    "1password",
    "lastpass",
    "bitwarden",
    "dashlane",
    "keypass",
    "keepass",
    "conda",
    "pip",
    "npm",
    "yarn",
    "pnpm",
    "homebrew",
    "apt",
    "yum",
    "chocolatey",
    "scoop",
    "winget",
    "cygwin",
    "wsl",
    "windows subsystem for linux",
    "terminal",
    "command line",
    "cli",
    "powershell",
    "bash",
    "zsh",
    "fish",
    "tmux",
    "screen",
    "htop",
    "top",
    "iotop",
    "iftop",
    "nethogs",
    "tcpdump",
    "netstat",
    "ss",
    "lsof",
    "strace",
    "gdb",
    "lldb",
    "valgrind",
    "perf",
    "oprofile",
    "flamegraph",
    "async-profiler",
    "jprofiler",
    "yourkit",
    "visualvm",
    "jconsole",
    "jcmd",
    "jstack",
    "jmap",
    "jhat",
    "mat",
    "memory analyzer",
    "heapprofiler",
    "allocation profiler",
    "leak canary",
    "instruments",
    "xcode instruments",
    "time profiler",
    "energy log",
    "network link conditioner",
    "simulator",
    "ios simulator",
    "android emulator",
    "genymotion",
    "bluestacks",
    "docker compose",
    "docker-compose",
    "docker swarm",
    "dockerfile",
    "container",
    "podman",
    "containerd",
    "cri-o",
    "rkt",
    "lxc",
    "lxd",
    "firecracker",
    "gvisor",
    "kata containers",
    "qemu",
    "virtualbox",
    "vmware",
    "hyper-v",
    "parallels",
    "xen",
    "kvm",
    "libvirt",
    "proxmox",
    "esxi",
    "vcenter",
    "citrix",
    "xenserver",
    "openstack",
    "cloudstack",
    "ovirt",
    "nagios",
    "icinga",
    "zabbix",
    "cacti",
    "munin",
    "observium",
    "librenms",
    "prtg",
    "solarwinds",
    "logicmonitor",
    "site24x7",
    "uptimerobot",
    "statuspage",
    "betterstack",
    "raygun",
    "airbrake",
    "honeybadger",
    "exceptional",
    "trackjs",
    "logrocket",
    "sentry",
    "glitchtip",
    "kibana",
    "grafana loki",
    "tempo",
    "mimir",
    "cortex",
    "thanos",
    "victoriametrics",
    "clickhouse",
    "druid",
    "pinot",
    "starrocks",
    "doris",
    "rockset",
    "materialize",
    "singlestore",
    "memsql",
    "timescale",
    "questdb",
    "kdb+",
    "influx",
    "telegraf",
    "kapacitor",
    "chronograf",
    "collectd",
    "statsd",
    "graphite",
    "carbon",
    "whisper",
    "riemann",
    "sensu",
    "fluentd",
    "fluentbit",
    "vector",
    "filebeat",
    "metricbeat",
    "heartbeat",
    "auditbeat",
    "packetbeat",
    "functionbeat",
    "winlogbeat",
    "journalbeat",
    "topbeat",
    "elastic agent",
    "fleet",
    "elastic cloud",
    "elasticsearch",
    "opensearch",
    "solr",
    "lucene",
  ],
  Databases: [
    "postgresql",
    "postgres",
    "mysql",
    "mariadb",
    "sqlite",
    "sql server",
    "mssql",
    "oracle",
    "db2",
    "mongodb",
    "cassandra",
    "redis",
    "memcached",
    "elasticsearch",
    "dynamodb",
    "firestore",
    "bigtable",
    "hbase",
    "neo4j",
    "couchdb",
    "couchbase",
    "influxdb",
    "clickhouse",
    "druid",
    "redshift",
    "bigquery",
    "snowflake",
    "databricks",
    "teradata",
    "vertica",
    "hive",
    "presto",
    "trino",
    "sqlite",
    "cubrid",
    "firebird",
    "derby",
    "hsqldb",
    "h2",
    "sqlanywhere",
    "interbase",
    "informix",
    "ingres",
    "sybase",
    "sap hana",
    "hana",
    "exasol",
    "dremio",
    "minio",
    "ceph",
    "glusterfs",
    "hdfs",
    "hadoop",
    "spark",
    "flink",
    "kafka",
    "pulsar",
    "rabbitmq",
    "activemq",
    "nats",
    "zookeeper",
    "etcd",
    "consul",
    "apache",
    "nginx",
    "caddy",
    "haproxy",
    "envoy",
    "istio",
    "linkerd",
    "consul connect",
    "service mesh",
    "traefik",
    "kong",
    "tyk",
    "apisix",
    "3scale",
    "mulesoft",
    "apigee",
    "aws api gateway",
    "azure api management",
    "google api gateway",
  ],
  Cloud: [
    "aws",
    "amazon web services",
    "azure",
    "microsoft azure",
    "gcp",
    "google cloud",
    "google cloud platform",
    "oracle cloud",
    "oci",
    "ibm cloud",
    "alibaba cloud",
    "aliyun",
    "tencent cloud",
    "digitalocean",
    "linode",
    "vultr",
    "heroku",
    "netlify",
    "vercel",
    "cloudflare",
    "fastly",
    "akamai",
    "render",
    "railway",
    "fly.io",
    "fly",
    "supabase",
    "firebase",
    "back4app",
    "parse",
    "appwrite",
    "pocketbase",
    "directus",
    "strapi",
    "sanity",
    "contentful",
    "prismic",
    "buttercms",
    "storyblok",
    "headless cms",
    "cms",
    "wordpress",
    "drupal",
    "keystone",
    "ghost",
  ],
  "Data & ML": [
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "ai",
    "nlp",
    "natural language processing",
    "computer vision",
    "cv",
    "reinforcement learning",
    "rl",
    "supervised learning",
    "unsupervised learning",
    "semi-supervised learning",
    "transfer learning",
    "federated learning",
    "active learning",
    "online learning",
    "batch learning",
    "ensemble learning",
    "bagging",
    "boosting",
    "stacking",
    "random forest",
    "decision tree",
    "gradient boosting",
    "xgboost",
    "lightgbm",
    "catboost",
    "adaboost",
    "gbm",
    "linear regression",
    "logistic regression",
    "polynomial regression",
    "ridge regression",
    "lasso",
    "elastic net",
    "support vector machine",
    "svm",
    "k-nearest neighbors",
    "knn",
    "naive bayes",
    "k-means",
    "dbscan",
    "hierarchical clustering",
    "pca",
    "principal component analysis",
    "lda",
    "tsne",
    "umap",
    "neural network",
    "neural networks",
    "cnn",
    "convolutional neural network",
    "rnn",
    "recurrent neural network",
    "lstm",
    "gru",
    "transformer",
    "transformers",
    "attention",
    "attention mechanism",
    "bert",
    "roberta",
    "gpt",
    "gpt-3",
    "gpt-4",
    "llm",
    "large language model",
    "large language models",
    "rag",
    "retrieval augmented generation",
    "fine-tuning",
    "fine tuning",
    "prompt engineering",
    "embedding",
    "embeddings",
    "tokenization",
    "tokenizer",
    "sentiment analysis",
    "text classification",
    "named entity recognition",
    "ner",
    "part-of-speech tagging",
    "pos tagging",
    "machine translation",
    "question answering",
    "qa",
    "summarization",
    "text summarization",
    "topic modeling",
    "topic modelling",
    "latent dirichlet allocation",
    "lda",
    "word2vec",
    "glove",
    "fasttext",
    "elmo",
    "data analysis",
    "data analytics",
    "data science",
    "data mining",
    "data engineering",
    "big data",
    "data pipeline",
    "etl",
    "elt",
    "data warehouse",
    "data lake",
    "data lakehouse",
    "data modeling",
    "data modelling",
    "data visualization",
    "data wrangling",
    "data cleaning",
    "data preprocessing",
    "feature engineering",
    "feature selection",
    "model evaluation",
    "cross-validation",
    "hyperparameter tuning",
    "hyperparameter optimization",
    "grid search",
    "random search",
    "bayesian optimization",
    "mlops",
    "ml flow",
    "mlflow",
    "kubeflow",
    "dvc",
    "dvc",
    "pachyderm",
    "model registry",
    "feature store",
    "feast",
    "tecton",
    "hopsworks",
    "statistics",
    "probability",
    "statistical modeling",
    "statistical analysis",
    "hypothesis testing",
    "a/b testing",
    "ab testing",
    "experimental design",
    "experimentation",
    "causal inference",
    "time series",
    "time series analysis",
    "forecasting",
    "predictive modeling",
    "predictive analytics",
    "prescriptive analytics",
    "descriptive analytics",
    "diagnostic analytics",
    "business intelligence",
    "bi",
    "reporting",
    "dashboards",
    "kpis",
    "metrics",
    "analytics",
    "olap",
    "oltp",
    "dimensional modeling",
    "star schema",
    "snowflake schema",
    "data governance",
    "data quality",
    "data profiling",
    "data lineage",
    "data catalog",
    "metadata",
    "master data management",
    "mdm",
    "data security",
    "data privacy",
    "data anonymization",
    "data encryption",
    "gdpr",
    "ccpa",
    "hipaa",
    "soc2",
    "iso 27001",
    "pci dss",
  ],
  "Soft Skills": [
    "leadership",
    "communication",
    "teamwork",
    "collaboration",
    "problem solving",
    "critical thinking",
    "analytical thinking",
    "analytical skills",
    "creativity",
    "innovation",
    "adaptability",
    "flexibility",
    "time management",
    "organization",
    "organizational skills",
    "project management",
    "agile",
    "scrum",
    "kanban",
    "waterfall",
    "lean",
    "six sigma",
    "pmbok",
    "pmp",
    "prince2",
    "risk management",
    "stakeholder management",
    "stakeholder communication",
    "client management",
    "customer service",
    "public speaking",
    "presentation skills",
    "writing skills",
    "technical writing",
    "documentation",
    "mentoring",
    "coaching",
    "teaching",
    "training",
    "negotiation",
    "conflict resolution",
    "decision making",
    "strategic planning",
    "strategic thinking",
    "business acumen",
    "entrepreneurship",
    "attention to detail",
    "multitasking",
    "prioritization",
    "delegation",
    "empathy",
    "emotional intelligence",
    "interpersonal skills",
    "team building",
    "cross-functional collaboration",
    "remote collaboration",
    "global collaboration",
    "customer-centric",
    "user-centric",
    "user empathy",
    "product sense",
    "product thinking",
    "growth mindset",
    "continuous learning",
    "agile mindset",
    "ownership",
    "accountability",
    "initiative",
    "self-motivation",
    "self-starter",
    "results-oriented",
    "goal-oriented",
    "detail-oriented",
    "data-driven",
    "data-driven decision making",
  ],
};

// Build a flat lookup map: normalized keyword -> category
const KEYWORD_TO_CATEGORY = new Map();
for (const [category, keywords] of Object.entries(SKILL_DICTIONARY)) {
  for (const keyword of keywords) {
    // Multi-word phrases must be matched as whole phrases in text,
    // but also allow matching within a normalized text blob.
    KEYWORD_TO_CATEGORY.set(keyword, category);
  }
}

// Display name map: normalized keyword -> prettified name for the UI.
const DISPLAY_NAMES = {
  c: "C",
  "c++": "C++",
  "c#": "C#",
  "f#": "F#",
  ".net": ".NET",
  "asp.net": "ASP.NET",
  "asp.net core": "ASP.NET Core",
  "node.js": "Node.js",
  "next.js": "Next.js",
  "react.js": "React",
  "vue.js": "Vue.js",
  "angularjs": "AngularJS",
  "react native": "React Native",
  "spring boot": "Spring Boot",
  "express.js": "Express.js",
  "d3.js": "D3.js",
  "tailwind css": "Tailwind CSS",
  "material-ui": "Material UI",
  "chakra ui": "Chakra UI",
  "scikit-learn": "scikit-learn",
  "sklearn": "scikit-learn",
  "hugging face": "Hugging Face",
  "apache spark": "Apache Spark",
  "apache kafka": "Apache Kafka",
  "rest api": "REST API",
  "socket.io": "Socket.io",
  "power bi": "Power BI",
  "ml": "Machine Learning",
  "dl": "Deep Learning",
  "nlp": "NLP",
  "cv": "Computer Vision",
  "rl": "Reinforcement Learning",
  "llm": "LLM",
  "rag": "RAG",
  "k8s": "Kubernetes",
  "mlops": "MLOps",
  "gcp": "Google Cloud",
  "aws": "AWS",
  "ci/cd": "CI/CD",
  "i18n": "i18n",
  "a11y": "Accessibility",
  "ui/ux": "UI/UX",
  "nodejs": "Node.js",
  "nextjs": "Next.js",
  "reactjs": "React",
  "vuejs": "Vue.js",
  "expressjs": "Express.js",
  "d3js": "D3.js",
  "tailwindcss": "Tailwind CSS",
  "machine learning": "Machine Learning",
  "deep learning": "Deep Learning",
  "artificial intelligence": "AI",
  "natural language processing": "NLP",
  "computer vision": "Computer Vision",
  "reinforcement learning": "Reinforcement Learning",
  "large language model": "LLM",
  "large language models": "LLM",
  "retrieval augmented generation": "RAG",
  "fine-tuning": "Fine-tuning",
  "fine tuning": "Fine-tuning",
  "prompt engineering": "Prompt Engineering",
  "sentiment analysis": "Sentiment Analysis",
  "text classification": "Text Classification",
  "named entity recognition": "NER",
  "part-of-speech tagging": "POS Tagging",
  "pos tagging": "POS Tagging",
  "machine translation": "Machine Translation",
  "question answering": "Question Answering",
  "text summarization": "Text Summarization",
  "topic modeling": "Topic Modeling",
  "topic modelling": "Topic Modeling",
  "latent dirichlet allocation": "LDA",
  "data analysis": "Data Analysis",
  "data analytics": "Data Analytics",
  "data science": "Data Science",
  "data mining": "Data Mining",
  "data engineering": "Data Engineering",
  "big data": "Big Data",
  "data pipeline": "Data Pipeline",
  "data warehouse": "Data Warehouse",
  "data lake": "Data Lake",
  "data lakehouse": "Data Lakehouse",
  "data modeling": "Data Modeling",
  "data modelling": "Data Modeling",
  "data visualization": "Data Visualization",
  "data wrangling": "Data Wrangling",
  "data cleaning": "Data Cleaning",
  "data preprocessing": "Data Preprocessing",
  "feature engineering": "Feature Engineering",
  "feature selection": "Feature Selection",
  "model evaluation": "Model Evaluation",
  "cross-validation": "Cross-validation",
  "hyperparameter tuning": "Hyperparameter Tuning",
  "hyperparameter optimization": "Hyperparameter Optimization",
  "grid search": "Grid Search",
  "random search": "Random Search",
  "bayesian optimization": "Bayesian Optimization",
  "ml flow": "MLflow",
  "model registry": "Model Registry",
  "feature store": "Feature Store",
  "statistical modeling": "Statistical Modeling",
  "statistical analysis": "Statistical Analysis",
  "hypothesis testing": "Hypothesis Testing",
  "a/b testing": "A/B Testing",
  "ab testing": "A/B Testing",
  "experimental design": "Experimental Design",
  "causal inference": "Causal Inference",
  "time series": "Time Series",
  "time series analysis": "Time Series Analysis",
  "predictive modeling": "Predictive Modeling",
  "predictive analytics": "Predictive Analytics",
  "prescriptive analytics": "Prescriptive Analytics",
  "descriptive analytics": "Descriptive Analytics",
  "diagnostic analytics": "Diagnostic Analytics",
  "business intelligence": "Business Intelligence",
  "dimensional modeling": "Dimensional Modeling",
  "star schema": "Star Schema",
  "snowflake schema": "Snowflake Schema",
  "data governance": "Data Governance",
  "data quality": "Data Quality",
  "data profiling": "Data Profiling",
  "data lineage": "Data Lineage",
  "data catalog": "Data Catalog",
  "master data management": "MDM",
  "data security": "Data Security",
  "data privacy": "Data Privacy",
  "data anonymization": "Data Anonymization",
  "data encryption": "Data Encryption",
  "soc2": "SOC 2",
  "iso 27001": "ISO 27001",
  "pci dss": "PCI DSS",
  "problem solving": "Problem Solving",
  "critical thinking": "Critical Thinking",
  "analytical thinking": "Analytical Thinking",
  "analytical skills": "Analytical Skills",
  "time management": "Time Management",
  "organizational skills": "Organizational Skills",
  "project management": "Project Management",
  "six sigma": "Six Sigma",
  "risk management": "Risk Management",
  "stakeholder management": "Stakeholder Management",
  "stakeholder communication": "Stakeholder Communication",
  "client management": "Client Management",
  "customer service": "Customer Service",
  "public speaking": "Public Speaking",
  "presentation skills": "Presentation Skills",
  "writing skills": "Writing Skills",
  "technical writing": "Technical Writing",
  "conflict resolution": "Conflict Resolution",
  "decision making": "Decision Making",
  "strategic planning": "Strategic Planning",
  "strategic thinking": "Strategic Thinking",
  "business acumen": "Business Acumen",
  "attention to detail": "Attention to Detail",
  "emotional intelligence": "Emotional Intelligence",
  "interpersonal skills": "Interpersonal Skills",
  "team building": "Team Building",
  "cross-functional collaboration": "Cross-functional Collaboration",
  "remote collaboration": "Remote Collaboration",
  "global collaboration": "Global Collaboration",
  "customer-centric": "Customer-centric",
  "user-centric": "User-centric",
  "user empathy": "User Empathy",
  "product sense": "Product Sense",
  "product thinking": "Product Thinking",
  "growth mindset": "Growth Mindset",
  "continuous learning": "Continuous Learning",
  "agile mindset": "Agile Mindset",
  "self-motivation": "Self-motivation",
  "self-starter": "Self-starter",
  "results-oriented": "Results-oriented",
  "goal-oriented": "Goal-oriented",
  "detail-oriented": "Detail-oriented",
  "data-driven": "Data-driven",
  "data-driven decision making": "Data-driven Decision Making",
  "supervised learning": "Supervised Learning",
  "unsupervised learning": "Unsupervised Learning",
  "semi-supervised learning": "Semi-supervised Learning",
  "transfer learning": "Transfer Learning",
  "federated learning": "Federated Learning",
  "active learning": "Active Learning",
  "online learning": "Online Learning",
  "batch learning": "Batch Learning",
  "ensemble learning": "Ensemble Learning",
  "random forest": "Random Forest",
  "decision tree": "Decision Tree",
  "gradient boosting": "Gradient Boosting",
  "adaboost": "AdaBoost",
  "linear regression": "Linear Regression",
  "logistic regression": "Logistic Regression",
  "polynomial regression": "Polynomial Regression",
  "ridge regression": "Ridge Regression",
  "elastic net": "Elastic Net",
  "support vector machine": "SVM",
  "k-nearest neighbors": "KNN",
  "naive bayes": "Naive Bayes",
  "k-means": "K-Means",
  "hierarchical clustering": "Hierarchical Clustering",
  "principal component analysis": "PCA",
  "neural network": "Neural Network",
  "neural networks": "Neural Network",
  "convolutional neural network": "CNN",
  "recurrent neural network": "RNN",
  "attention mechanism": "Attention Mechanism",
  "amazon web services": "AWS",
  "microsoft azure": "Azure",
  "google cloud platform": "Google Cloud Platform",
  "github actions": "GitHub Actions",
  "gitlab ci": "GitLab CI",
  "azure devops": "Azure DevOps",
  "azure pipelines": "Azure Pipelines",
  "react-hook-form": "React Hook Form",
  "redux toolkit": "Redux Toolkit",
};

/**
 * Normalize resume text for keyword matching:
 * - lowercase
 * - collapse whitespace
 * - remove separator punctuation (commas, semicolons, etc.)
 * - keep periods so multi-word tech names like "node.js" stay intact
 */
function normalizeText(text) {
  return text
    .toLowerCase()
    .replace(/\s+/g, " ")
    .replace(/[,;:!?()\[\]{}"']+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Extract structured skills from raw resume text.
 *
 * @param {string} text - Raw extracted resume text.
 * @returns {Object} - { skills: [{ name, category }], categories: { Category: [names] } }
 */
function extractSkills(text) {
  if (!text || typeof text !== "string" || text.trim().length === 0) {
    return { skills: [], categories: {} };
  }

  const normalized = normalizeText(text);
  const found = new Map(); // normalized keyword -> { name, category }
  const foundSoFar = new Set();

  // Sort keywords by length descending so multi-word phrases (e.g.
  // "react native") are matched before their substrings ("react").
  const sortedKeywords = [...KEYWORD_TO_CATEGORY.keys()].sort(
    (a, b) => b.length - a.length
  );

  for (const keyword of sortedKeywords) {
    if (foundSoFar.has(keyword)) continue;

    // Match keyword as a whole word/phrase (escaped regex).
    // Periods are allowed inside keywords (e.g. "node.js") but are not
    // treated as boundary characters, so "c" won't match inside "react".
    const escaped = keyword.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(`(^|[^a-z0-9+#])${escaped}([^a-z0-9+#]|$)`, "i");

    if (regex.test(normalized)) {
      const category = KEYWORD_TO_CATEGORY.get(keyword);
      const displayName = DISPLAY_NAMES[keyword] || toTitleCase(keyword);

      // Prefer the canonical display name; avoid duplicates like
      // "React" appearing twice via "react" and "react.js".
      const dedupeKey = displayName.toLowerCase();
      if (!foundSoFar.has(dedupeKey)) {
        foundSoFar.add(dedupeKey);
        found.set(dedupeKey, { name: displayName, category });
      }
    }
  }

  const skills = [...found.values()];

  // Group by category for structured output.
  const categories = {};
  for (const skill of skills) {
    if (!categories[skill.category]) {
      categories[skill.category] = [];
    }
    categories[skill.category].push(skill.name);
  }

  return { skills, categories };
}

/** Convert a lowercase keyword to a nicety Title Case display name. */
function toTitleCase(str) {
  return str
    .split(/[\s._-]+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

module.exports = { extractSkills };